version: "3.9"

services:
  app:
    build: .
    container_name: storelab_app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - storelab_net
    volumes:
      - ./images:/app/images
      - ./src/views:/app/src/views

  mongo:
    image: mongo:6
    container_name: storelab_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - storelab_net

volumes:
  mongo_data:

networks:
  storelab_net:
